In [3]:
import numpy as np 

y_predicted=np.array([1,1,0,0,1])
y_true=np.array([0.30,0.7,1,0,0.5])

In [6]:
#mean absolute error 
def mae(y_true,y_predicted):
    total_error=0
    for yt,yp in zip(y_true,y_predicted):
        total_error += abs(yt-yp)
    print("Total error:",total_error)
    
    mae=total_error/len(y_true)
    print("MAE:",mae)
    return mae

In [7]:
mae(y_true,y_predicted)

Total error: 2.5
MAE: 0.5


0.5

In [9]:
y_predicted-y_true

array([ 0.7,  0.3, -1. ,  0. ,  0.5])

In [10]:
np.mean(np.abs(y_predicted-y_true))

0.5

In [20]:
#log loss or binary cross entropy 
np.log([0.00001])

array([-11.51292546])

In [21]:
eplison=1e-15

In [29]:
y_predicted_new=[max(i,eplison)for i in y_predicted_new]
y_predicted_new 

[0.999999999999999, 0.999999999999999, 1e-15, 1e-15, 0.999999999999999]

In [30]:
y_predicted_new=[min(i,1-eplison)for i in y_predicted_new ]
y_predicted_new

[0.999999999999999, 0.999999999999999, 1e-15, 1e-15, 0.999999999999999]

In [31]:
y_predicted_new=np.array(y_predicted_new)
np.log(y_predicted_new)

array([-9.99200722e-16, -9.99200722e-16, -3.45387764e+01, -3.45387764e+01,
       -9.99200722e-16])

In [34]:
#log loss
def log_loss(y_true,y_predicted):
    eplison=1e-15
    y_predicted_new=[max(i,eplison)for i in y_predicted ]
    y_predicted_new=[min(i,1-eplison)for i in y_predicted_new ]
    y_predicted_new=np.array(y_predicted_new)
    return -np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

In [35]:
log_loss(y_true,y_predicted)

17.2696280766844